language: python
python:
  - "2.7"
  - "3.6"

install:
  - pip install -r requirements.txt
  - pip install -r test-requirements.txt
  - python setup.py build
  - python setup.py install

# command to run tests
script:
  - flake8 --ignore=E305,E302 hdrh test
  - pylint --rcfile pylint.rc hdrh test
  - py.test -s
